import React, { useEffect, useMemo, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { api } from "../lib/api.js";
import Toast from "../components/Toast.jsx";
import InfoBox from "../components/InfoBox.jsx";
import { getRole } from "../lib/session.js";

export default function ResourcesPage() {
  const role = getRole();
  const isTeacher = role === "teacher";
  const { moduleId } = useParams();

  const [items, setItems] = useState([]);
  const [err, setErr] = useState("");
  const [selected, setSelected] = useState(null);
  const [content, setContent] = useState("");
  const [newTitle, setNewTitle] = useState("");

  const studyGuides = useMemo(
    () => items.filter((x) => x.type === "study_guide"),
    [items]
  );

  // teacher has editor panel always (right side), student does not
  const showEditor = isTeacher;

  async function refresh() {
    try {
      setErr("");
      const res = await api.listResources(moduleId);
      setItems(res || []);
    } catch (e) {
      setErr(e.message);
    }
  }

  useEffect(() => {
    refresh();
    const mid = Number(moduleId);
    if (Number.isFinite(mid) && mid > 0) {
      localStorage.setItem("t_last_module_id", String(mid));
    }
  }, [moduleId]);

  async function loadStudyGuideForEditing(resource) {
    try {
      setErr("");
      setSelected(resource);
      const full = await api.getResource(resource.id);
      setContent(full.content || "");
    } catch (e) {
      setErr(e.message);
    }
  }

  async function saveContent() {
    try {
      setErr("");
      if (!selected) throw new Error("Select a study guide first.");
      await api.patchResourceContent(selected.id, content);
      setErr("✅ Saved study material.");
      await refresh();
    } catch (e) {
      setErr(e.message);
    }
  }

  async function generateQuestions(resourceId) {
    try {
      setErr("");
      const out = await api.generateQuestionsFromResource({ resource_id: resourceId, n: 10 });
      setErr(`✅ Created ${out.count} questions.`);
    } catch (e) {
      setErr(e.message);
    }
  }

  async function generateFlashcards(resourceId) {
    try {
      setErr("");
      const out = await api.generateFlashcardsFromResource({ resource_id: resourceId, n: 10 });
      setErr(`✅ Created ${out.count} flashcards.`);
      await refresh();
    } catch (e) {
      setErr(e.message);
    }
  }

  async function createStudyGuide() {
    try {
      setErr("");
      const out = await api.createResource({
        module_id: Number(moduleId),
        type: "study_guide",
        title: newTitle?.trim() || `Study Guide - Module ${moduleId}`,
        file_type: "txt",
        file_path: "generated",
        uploaded_by: 1,
      });
      setErr(`✅ Created study guide #${out.id}.`);
      setNewTitle("");
      await refresh();
    } catch (e) {
      setErr(e.message);
    }
  }

  return (
    <div style={{ display: "grid", gap: 12 }}>
      <div>
        <h2 style={{ margin: 0 }}>Resources for Module #{moduleId}</h2>
        <div style={{ color: "rgba(255,255,255,.7)", marginTop: 6 }}>
          {isTeacher ? "Manage study guides and generate learning content." : "Browse material and practice."}
        </div>
      </div>

      <InfoBox title={isTeacher ? "Teacher: Study material → AI" : "Student: Study material"}>
        {isTeacher ? (
          <>
            <div>• Click <span className="badge">Edit content</span> on a study guide.</div>
            <div>• Edit on the right → <b>Save material</b> → generate questions/flashcards.</div>
          </>
        ) : (
          <>
            <div>• Open resources and take quizzes generated by your teacher.</div>
            <div>• Use flashcards for quick revision.</div>
          </>
        )}
      </InfoBox>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: showEditor ? "1.1fr 0.9fr" : "1fr",
          gap: 12,
          alignItems: "start",
        }}
      >
        {/* LEFT */}
        <div style={{ display: "grid", gap: 12 }}>
          {showEditor && (
            <div className="card">
              <div style={{ fontWeight: 900, marginBottom: 10 }}>Create Study Guide</div>
              <div className="row">
                <input
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="Title (optional)"
                />
                <button className="btn btn-primary" onClick={createStudyGuide}>
                  Create
                </button>
              </div>
            </div>
          )}

          <div style={{ display: "grid", gap: 10 }}>
            <h3 style={{ margin: 0 }}>{isTeacher ? "Resources List" : "Available Material"}</h3>

            {items.length === 0 ? (
              <div className="card" style={{ color: "rgba(255,255,255,.7)" }}>
                No resources yet.
              </div>
            ) : (
              items.map((r) => (
                <div key={r.id} className="card" style={{ display: "grid", gap: 10 }}>
                  <div style={{ fontWeight: 900 }}>
                    {r.title}
                    <span style={{ marginLeft: 10, fontSize: 12, color: "rgba(255,255,255,.55)" }}>
                      #{r.id} • {r.type}
                    </span>
                  </div>

                  {showEditor && (
                    <div style={{ fontSize: 12, color: "rgba(255,255,255,.55)" }}>
                      file_type: {r.file_type} | file_path: {r.file_path}
                    </div>
                  )}

                  {/* ✅ LEFT ACTIONS: simplified */}
                  <div className="row">
                    {showEditor && r.type === "study_guide" && (
                      <button className="btn" onClick={() => loadStudyGuideForEditing(r)}>
                        Edit content
                      </button>
                    )}

                    {r.type === "flashcard" && (
                      <Link className="btn" to={`/flashcards/${moduleId}`}>
                        View flashcards
                      </Link>
                    )}

                    {!showEditor && r.type === "study_guide" && (
                      <>
                        <Link className="btn btn-primary" to={`/adaptive/${moduleId}`}>
                          Take quiz
                        </Link>
                        <Link className="btn" to={`/flashcards/${moduleId}`}>
                          Flashcards
                        </Link>
                      </>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>

          {/* ✅ bottom actions: NOT a huge card */}
          <div className="row" style={{ marginTop: 6 }}>
            {showEditor && (
              <Link className="btn" to={`/questions/module/${moduleId}`}>
                View all questions (module)
              </Link>
            )}
            <Link className="btn" to={`/adaptive/${moduleId}`}>
              Adaptive quiz (module)
            </Link>
          </div>
        </div>

        {/* RIGHT: editor */}
        {showEditor && (
          <div style={{ display: "grid", gap: 10 }}>
            <h3 style={{ margin: 0 }}>Study Guide editor</h3>

            {studyGuides.length === 0 ? (
              <div style={{ color: "rgba(255,255,255,.7)" }}>No study_guide resources found.</div>
            ) : !selected ? (
              <div style={{ color: "rgba(255,255,255,.7)" }}>
                Select a <span className="badge">study_guide</span> from the list to edit.
              </div>
            ) : (
              <div className="card" style={{ display: "grid", gap: 10 }}>
                <div style={{ fontWeight: 900 }}>
                  Editing: {selected.title}
                  <span style={{ marginLeft: 10, fontSize: 12, color: "rgba(255,255,255,.55)" }}>
                    #{selected.id}
                  </span>
                </div>

                <textarea
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  rows={14}
                  placeholder="Paste study material here…"
                />

                {/* ✅ RIGHT BUTTONS: exactly what you asked */}
                <div className="row">
                  <button className="btn btn-primary" onClick={saveContent} disabled={!content.trim()}>
                    Save material
                  </button>

                  <button className="btn" onClick={() => generateQuestions(selected.id)} disabled={!content.trim()}>
                    Generate questions
                  </button>

                  <button className="btn" onClick={() => generateFlashcards(selected.id)} disabled={!content.trim()}>
                    Generate flashcards
                  </button>

                  <Link className="btn" to={`/questions/resource/${selected.id}`}>
                    View Questions
                  </Link>
                </div>

                {/* optional helper */}
                <div style={{ fontSize: 12, color: "rgba(255,255,255,.55)" }}>
                  Tip: Save first → then generate, so the AI uses the latest content.
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      <Toast message={err} onClose={() => setErr("")} />
    </div>
  );
}
